<%@ page language="java" pageEncoding="UTF-8"%>
<%@ page import="com.cathaylife.campaign2016.insurance.q1.model.*" %>
<%@ page import="com.cathaylife.campaign2016.insurance.q1.dao.*" %>
<%@ page import="com.cathaylife.campaign2016.insurance.q4.util.CliaConst" %>
<%@ page import="java.io.*" %>
<%@ page import="java.sql.*" %>
<%@ page import="java.util.*" %>
<%@ page import="java.net.*" %>
<%@ page import="org.apache.commons.lang.*" %>
<%@ page import="org.json.*" %>
<%@ page import="jxl.*" %>
<%@ page import="jxl.format.*" %>
<%@ page import="jxl.write.*" %>